#!/bin/bash

echo 'Setting Environment Variables'
export GRADLE_USER_HOME=$OPENSHIFT_DATA_DIR/gradle

echo 'Entering OpenShift Repo Directory'
cd $OPENSHIFT_REPO_DIR

echo 'Building WAR file'
chmod +x gradlew
./gradlew war
mv build/libs/*.war diy/glassfish4/glassfish/domains/domain1/autodeploy/

# echo 'Batch loading SQL files to MySQL'
# cd sql/
# ls -1 *.sql | awk '{ print "source",$0 }' | mysql --batch

echo 'Terminating build script'
cd $OPENSHIFT_REPO_DIR